# Change these first
owner: mathscircle # Your GitHub organization or username, where this repository lives
repo: status-upptime # The name of this repository

sites:
  - name: Play TTRS
    url: https://play.ttrockstars.com
  - name: TTRS API
    url: https://mcpugs.ttrockstars.com
  - name: TTRS Nest API
    url: https://nest.ttrockstars.com
  - name: TTRS Rockbase
    url: https://rockbase.ttrockstars.com
  - name: TTRS Website
    url: https://ttrockstars.com
  - name: NumBots Login
    url: https://auth.numbots.com/api
  - name: NumBots API
    url: https://stats.numbots.com/api
  - name: NumBots website
    url: https://numbots.com
 # - name: IPv6 website
 #   url: forwardemail.net
 #   port: 80
 #   check: "tcp-ping"
 #   ipv6: true

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.mathscircle.com
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/mathscircle/status-upptime/master/static/img/all_logo.gif
  name: Maths Circle
  introTitle: "Our vision: Every child grows up to say **\"I am good at maths\"** "
  introMessage: Maths Circle is an internationally trusted EdTech company who create award-winning maths programmes, dedicated to helping children acquire fundamental numeracy skills.
  navbar:
    - title: Our Sites Status
      href: /
    - title: Maths Circle
      href: https://mathscircle.com

workflowSchedule:
  graphs: "0 0 * * *"
  responseTime: "0 23 * * *"
  staticSite: "0 1 * * *"
  summary: "0 0 * * *"
  updateTemplate: "0 0 * * *"
  updates: "0 3 * * *"
  uptime: "*/10 * * * *"  #set to once every 10 minutes to reduce build minutes.

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
